-- DDL generated by Postico 2.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE personal.food_dict (
    id integer DEFAULT nextval('personal.food_dict_id_seq'::regclass) PRIMARY KEY,
    product text UNIQUE,
    kcal_100 numeric(6,2),
    protein_100 numeric(6,2),
    fat_100 numeric(6,2),
    carbs_100 numeric(6,2),
    source text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX food_dict_pkey ON personal.food_dict(id int4_ops);
CREATE UNIQUE INDEX food_dict_product_key ON personal.food_dict(product text_ops);
