-- DDL generated by Postico 2.3
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE personal.food_log (
    id bigint DEFAULT nextval('personal.food_log_id_seq'::regclass) PRIMARY KEY,
    meal_type text NOT NULL,
    product text NOT NULL,
    quantity_g integer NOT NULL CHECK (quantity_g > 0),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_at_am timestamp without time zone GENERATED ALWAYS AS ((created_at AT TIME ZONE 'Asia/Yerevan'::text)) STORED
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX food_log_pkey ON personal.food_log(id int8_ops);
CREATE INDEX idx_food_log_created_at ON personal.food_log(created_at timestamptz_ops DESC);
CREATE INDEX idx_food_log_meal_type ON personal.food_log(meal_type text_ops);
CREATE INDEX idx_food_log_product_ci ON personal.food_log((lower(product)) text_ops);
